// analyze API 对文本字符串进行 analysis
// https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-analyze.html

### 使用 standard analyzer
### 以 [Unicode Text Segmentation](http://unicode.org/reports/tr29/) 算法分词
GET http://localhost:9200/_analyze
Content-Type: application/json

{
    "analyzer": "standard",
    "text": "The 2 QUICK Brown-Foxes jumped over the lazy dog's bone."
}

### 使用 simple analyzer
### 以字母分词
GET http://localhost:9200/_analyze
Content-Type: application/json

{
    "analyzer": "simple",
    "text": "The 2 QUICK Brown-Foxes jumped over the lazy dog's bone."
}

### 使用 whitespace analyzer
### 以空格分词
GET http://localhost:9200/_analyze
Content-Type: application/json

{
    "analyzer": "whitespace",
    "text": "The 2 QUICK Brown-Foxes jumped over the lazy dog's bone."
}

### 使用 pattern analyzer
### 以正则表达式分词，默认正则表达式值是 \W+
GET http://localhost:9200/_analyze
Content-Type: application/json

{
    "analyzer": "pattern",
    "text": "The 2 QUICK Brown-Foxes jumped over the lazy dog's bone."
}