### Compact and aligned text (CAT) APIs
### https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-cat

### cat count API
### https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-cat-count
GET http://localhost:9200/_cat/count?v
Content-Type: application/json

### cat health API
### https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-cat-health
GET http://localhost:9200/_cat/health?v
Content-Type: application/json

### cat indices API
### https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-cat-indices
GET http://localhost:9200/_cat/indices?v
Content-Type: application/json

### cat master API
### https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-cat-master
GET http://localhost:9200/_cat/master?v
Content-Type: application/json

### cat nodes API
### https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-cat-nodes
GET http://localhost:9200/_cat/nodes?v&h=ip,port,heapPercent,name
Content-Type: application/json

### cat shards API
### https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-cat-shards
GET http://localhost:9200/_cat/shards?v
Content-Type: application/json

### cat thread pool API
### https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-cat-thread-pool
GET http://localhost:9200/_cat/thread_pool?v
Content-Type: application/json
