### Compact and aligned text (CAT) APIs
### https://www.elastic.co/guide/en/elasticsearch/reference/current/cat.html

### cat count API
### https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-count.html
GET http://localhost:9200/_cat/count?v
Content-Type: application/json

### cat health API
### https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-health.html
GET http://localhost:9200/_cat/health?v
Content-Type: application/json

### cat indices API
### https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html
GET http://localhost:9200/_cat/indices?v
Content-Type: application/json

### cat master API
### https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-master.html
GET http://localhost:9200/_cat/master?v
Content-Type: application/json

### cat nodes API
### https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html
GET http://localhost:9200/_cat/nodes?v&h=ip,port,heapPercent,name
Content-Type: application/json

### cat shards API
### https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html
GET http://localhost:9200/_cat/shards?v
Content-Type: application/json

### cat thread pool API
### https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-thread-pool.html
GET http://localhost:9200/_cat/thread_pool?v
Content-Type: application/json