### Document APIs
### https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-document

### Index API
### https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-create
# PUT http://localhost:9200/bank/_doc/test
PUT http://localhost:9200/bank/_create/test
Content-Type: application/json

{
  "account_number": 1,
  "balance": 999,
  "firstname": "Mao",
  "lastname": "Fantastic",
  "age": 25,
  "gender": "M",
  "address": "Earth",
  "employer": "Mao Boss",
  "email": "maomao@gmail.com",
  "city": "HangZhou",
  "state": "ZheJiang"
}

### Get API
### https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-get
GET http://localhost:9200/bank/_doc/test
Content-Type: application/json

### Get API
### https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-get
HEAD http://localhost:9200/bank/_doc/test
Content-Type: application/json

### Get API
### https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-get
GET http://localhost:9200/bank/_source/test
Content-Type: application/json

### Get API
### https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-get
HEAD http://localhost:9200/bank/_source/test
Content-Type: application/json

### Delete API
### https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-delete
DELETE http://localhost:9200/bank/_doc/test
Content-Type: application/json

### Bulk API
### https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-bulk
POST http://localhost:9200/bank/_bulk
Content-Type: application/x-ndjson

< bank_data.ndjson
