### Index APIs
### https://www.elastic.co/guide/en/elasticsearch/reference/current/indices.html

### Create index API
### https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html
PUT http://localhost:9200/bank
Content-Type: application/json

< bank_mapping.json

### Get index API
### https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-index.html
GET http://localhost:9200/bank
Content-Type: application/json

### Delete index API
### https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-delete-index.html
GET http://localhost:9200/bank
Content-Type: application/json

### Get mapping API
### https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html
GET http://localhost:9200/bank/_mapping
Content-Type: application/json

### Get field mapping API
### https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-field-mapping.html
GET http://localhost:9200/bank/_mapping/field/account_number
Content-Type: application/json