// mapping API
// https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html

### 查看 mappping
GET http://localhost:9200/bank/_mapping
Content-Type: application/json

###
GET http://localhost:9200/bank/_mapping/field/account_number
Content-Type: application/json

### 创建自定义 mappping 的 index
PUT http://localhost:9200/bank
Content-Type: application/json

< bank_data.ndjson