### search API
### https://www.elastic.co/docs/api/doc/elasticsearch/group/endpoint-search

### Match query(full-text search)
### https://www.elastic.co/docs/reference/query-languages/query-dsl/query-dsl-match-query
GET http://localhost:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "address": {
        "query": "mill lane",
        "analyzer": "whitespace",
        "operator": "OR"
      }
    }
  }
}

### Match phrase query
### https://www.elastic.co/docs/reference/query-languages/query-dsl/query-dsl-match-query-phrase
GET http://localhost:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "match_phrase": {
      "address": {
        "query": "mill lane",
        "analyzer": "whitespace"
      }
    }
  }
}

### Multi-match query
### https://www.elastic.co/docs/reference/query-languages/query-dsl/query-dsl-multi-match-query
GET http://localhost:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "multi_match": {
      "query": "Duke",
      "fields": [
        "firstname",
        "lastname"
      ]
    }
  }
}

### IDs
### https://www.elastic.co/docs/reference/query-languages/query-dsl/query-dsl-ids-query
GET http://localhost:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "ids": {
      "values": [
        1,
        2,
        3
      ]
    }
  }
}

### Range query
### https://www.elastic.co/docs/reference/query-languages/query-dsl/query-dsl-range-query
GET http://localhost:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "range": {
      "age": {
        "gte": 25,
        "lte": 30
      }
    }
  }
}

### Term query
### https://www.elastic.co/docs/reference/query-languages/query-dsl/query-dsl-term-query
GET http://localhost:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "term": {
      "age": 40
    }
  }
}


### Terms query
### https://www.elastic.co/docs/reference/query-languages/query-dsl/query-dsl-terms-query
GET http://localhost:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "terms": {
      "age": [
        39,
        40
      ]
    }
  }
}

### Boolean query
### https://www.elastic.co/docs/reference/query-languages/query-dsl/query-dsl-bool-query
GET http://localhost:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "state": "UT"
          }
        },
        {
          "term": {
            "gender": "F"
          }
        }
      ],
      "filter": [
        {
          "range": {
            "age": {
              "gte": 18,
              "lt": 30
            }
          }
        }
      ]
    }
  },
  "sort": [
    {
      "age": "asc"
    },
    {
      "account_number": "asc"
    }
  ]
}
