CREATE DATABASE IF NOT EXISTS demo
  DEFAULT CHARSET 'utf8mb4';

USE demo;

CREATE TABLE IF NOT EXISTS user (
  id   INT     NOT NULL AUTO_INCREMENT,
  name CHAR(8) NOT NULL DEFAULT '',
  PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARSET 'utf8mb4';