// index API
// https://www.elastic.co/guide/en/elasticsearch/reference/current/indices.html

### 创建 index
PUT http://localhost:9200/bank
Content-Type: application/json

### 创建自定义 mappping 的 index
PUT http://localhost:9200/bank
Content-Type: application/json

{
  "mappings": {
    "properties": {
      "account_number": {
        "type": "integer"
      },
      "balance": {
        "type": "long"
      },
      "firstname": {
        "type": "keyword"
      },
      "lastname": {
        "type": "keyword"
      },
      "age": {
        "type": "integer"
      },
      "gender": {
        "type": "keyword"
      },
      "address": {
        "type": "text"
      },
      "employer": {
        "type": "keyword"
      },
      "email": {
        "type": "text"
      },
      "city": {
        "type": "keyword"
      },
      "state": {
        "type": "keyword"
      }
    }
  }
}

### 查看 index
GET http://localhost:9200/bank
Content-Type: application/json

### 删除 index
DELETE http://localhost:9200/bank
Content-Type: application/json

### 批量新增 document 至 index
POST http://localhost:9200/bank/_bulk
Content-Type: application/x-ndjson

< ./accounts.json