// search API
// https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html

// 按 _id 查询
GET http://localhost:9200/bank/_doc/1
Content-Type: application/json

### 精确查询
GET http://localhost:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "term": {
      "age": 40
    }
  }
}


### 多值精确查询
GET http://localhost:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "terms": {
      "age": [
        39,
        40
      ]
    }
  }
}

### 全文本匹配
GET http://localhost:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "address": {
        "query": "mill lane",
        "operator": "or"
      }
    }
  },
  "highlight": {
    "fields": {
      "address": {}
    }
  }
}

### 多字段全文本匹配
GET http://localhost:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "multi_match": {
      "query": "Duke",
      "fields": [
        "firstname",
        "lastname"
      ]
    }
  }
}

### 短语匹配
GET http://localhost:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "match_phrase": {
      "address": {
        "query": "mill lane"
      }
    }
  }
}

### 复合查询 Boolean Query
GET http://localhost:9200/bank/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "state": "UT"
          }
        },
        {
          "term": {
            "gender": "F"
          }
        }
      ],
      "filter": [
        {
          "range": {
            "age": {
              "gte": 18,
              "lt": 30
            }
          }
        }
      ]
    }
  },
  "sort": [
    {
      "age": "asc"
    },
    {
      "account_number": "asc"
    }
  ]
}